name: Infra-Create-Destroy (for-each)

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: ResourceGroupVars
- group: NetworkVars
- group: VMVars

# resources:
#   repositories:
#     - repository: terraformRepo
#       type: github
#       name: vamshii7/Terraform-Hands-On
#       ref: main
#       endpoint: github.com_vamshii7

stages:
- stage: Deploy
  displayName: "Deploy Infra"
  condition: eq(variables['Build.Reason'], 'Manual')
  jobs:
  - job: Terraform_Apply
    displayName: "Terraform Apply"
    steps:
    - checkout: self

    - task: TerraformInstaller@1
      displayName: "Install Terraform"
      inputs:
        terraformVersion: '1.13.3'

    # Write variable groups into tfvars.json files
    - script: |
        echo '$(resource_groups)' > resource_groups.auto.tfvars.json
        echo '$(network_details)' > network_details.auto.tfvars.json
        echo '$(vm_details)' > vm_details.auto.tfvars.json
      workingDirectory: '$(Build.SourcesDirectory)/Terraform+CI-CD/for-each'
      displayName: "Write variable groups to tfvars.json"

    - task: TerraformTaskV4@4
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Build.SourcesDirectory)/Terraform+CI-CD/for-each'
        backendServiceArm: 'TerraformConnection'
        backendAzureRmResourceGroupName: 'tfstate-rg'
        backendAzureRmStorageAccountName: 'temptfstatesa'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'foreach.tfstate'

    - task: TerraformTaskV4@4
      displayName: "Terraform Plan"
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(Build.SourcesDirectory)/Terraform+CI-CD/for-each'
        environmentServiceNameAzureRM: 'TerraformConnection'
        commandOptions: >
          -input=false

    - task: TerraformTaskV4@4
      displayName: "Terraform Apply"
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(Build.SourcesDirectory)/Terraform+CI-CD/for-each'
        environmentServiceNameAzureRM: 'TerraformConnection'
        commandOptions: >
          --auto-approve
          -input=false

- stage: Approval
  displayName: "Manual Approval Before Destroy"
  dependsOn: Deploy
  condition: succeeded()
  jobs:
  - job: WaitForApproval
    pool: server
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440
      inputs:
        instructions: |
          Approve to proceed with destruction of Infra.
        onTimeout: 'reject'

- stage: Destroy
  displayName: "Destroy Infra"
  dependsOn: Approval
  condition: eq(dependencies.Approval.result, 'Succeeded')
  jobs:
  - job: Terraform_Destroy
    displayName: "Terraform Destroy"
    steps:
    - checkout: self

    - task: TerraformInstaller@1
      displayName: "Install Terraform"
      inputs:
        terraformVersion: '1.13.3'

    - script: |
        echo '$(resource_groups)' > resource_groups.auto.tfvars.json
        echo '$(network_details)' > network_details.auto.tfvars.json
        echo '$(vm_details)' > vm_details.auto.tfvars.json
      workingDirectory: '$(Build.SourcesDirectory)/Terraform+CI-CD/for-each'
      displayName: "Write variable groups to tfvars.json"

    - task: TerraformTaskV4@4
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Build.SourcesDirectory)/Terraform+CI-CD/for-each'
        backendServiceArm: 'TerraformConnection'
        backendAzureRmResourceGroupName: 'tfstate-rg'
        backendAzureRmStorageAccountName: 'temptfstatesa'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'foreach.tfstate'

    - task: TerraformTaskV4@4
      displayName: "Terraform Destroy"
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        workingDirectory: '$(Build.SourcesDirectory)/Terraform+CI-CD/for-each'
        environmentServiceNameAzureRM: 'TerraformConnection'
        commandOptions: >
          --auto-approve
          -input=false